package com.keroles.Pharmacy.Model.Entity;
// Generated Oct 22, 2021, 2:07:56 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import static com.keroles.Pharmacy.Constant.ConstantDbProperties.*;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "company",
        catalog = "pharmacy"
)
//@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class,property = "companyId")

public class Company implements java.io.Serializable {

    private Integer companyId;
    private Address address;
    private String name;
    private String phone;
    private String logo;
    private Set<Drugs> drugses = new HashSet(0);

    public Company() {
    }

    public Company(Address address, String name, String phone) {
        this.address = address;
        this.name = name;
        this.phone = phone;
    }

    public Company(Address address, String name, String phone, String logo, Set<Drugs> drugses) {
        this.address = address;
        this.name = name;
        this.phone = phone;
        this.logo = logo;
        this.drugses = drugses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = table_company_attribut_company_id, unique = true, nullable = false)
    public Integer getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JsonBackReference(value = "company-address")
    @JoinColumn(name = table_company_attribut_address_id, nullable = false)
    public Address getAddress() {
        return this.address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    @Column(name = table_company_attribut_company_name, nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = table_company_attribut_company_phone, nullable = false, length = 20)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = table_company_attribut_company_logo, length = 16777215)
    public String getLogo() {
        return this.logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
    @JsonManagedReference(value = "drugs-company")

    public Set<Drugs> getDrugses() {
        return this.drugses;
    }

    public void setDrugses(Set<Drugs> drugses) {
        this.drugses = drugses;
    }

}
