package com.keroles.Pharmacy.Model.Entity;
// Generated Oct 22, 2021, 2:07:56 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonManagedReference;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeliveryMan generated by hbm2java
 */
@Entity
@Table(name="delivery_man"
    ,catalog="pharmacy"
)
public class DeliveryMan  implements java.io.Serializable {


     private Integer deliveryManId;
     private String deliveryManName;
     private long deliveryManPhone;
     private double deliveryManLat;
     private double deliveryManLong;
     private long deliveryManNationalId;
     private float deliveryManTotalRate;
     private int deliveryManRateCount;
     private int deliveryManAddressId;
     private Set<Order> orders = new HashSet(0);

    public DeliveryMan() {
    }

	
    public DeliveryMan(String deliveryManName, long deliveryManPhone, double deliveryManLat, double deliveryManLong, long deliveryManNationalId, float deliveryManTotalRate, int deliveryManRateCount, int deliveryManAddressId) {
        this.deliveryManName = deliveryManName;
        this.deliveryManPhone = deliveryManPhone;
        this.deliveryManLat = deliveryManLat;
        this.deliveryManLong = deliveryManLong;
        this.deliveryManNationalId = deliveryManNationalId;
        this.deliveryManTotalRate = deliveryManTotalRate;
        this.deliveryManRateCount = deliveryManRateCount;
        this.deliveryManAddressId = deliveryManAddressId;
    }
    public DeliveryMan(String deliveryManName, long deliveryManPhone, double deliveryManLat, double deliveryManLong, long deliveryManNationalId, float deliveryManTotalRate, int deliveryManRateCount, int deliveryManAddressId, Set<Order> orders) {
       this.deliveryManName = deliveryManName;
       this.deliveryManPhone = deliveryManPhone;
       this.deliveryManLat = deliveryManLat;
       this.deliveryManLong = deliveryManLong;
       this.deliveryManNationalId = deliveryManNationalId;
       this.deliveryManTotalRate = deliveryManTotalRate;
       this.deliveryManRateCount = deliveryManRateCount;
       this.deliveryManAddressId = deliveryManAddressId;
       this.orders = orders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="DELIVERY_MAN_ID", unique=true, nullable=false)
    public Integer getDeliveryManId() {
        return this.deliveryManId;
    }
    
    public void setDeliveryManId(Integer deliveryManId) {
        this.deliveryManId = deliveryManId;
    }

    
    @Column(name="DELIVERY_MAN_NAME", nullable=false, length=100)
    public String getDeliveryManName() {
        return this.deliveryManName;
    }
    
    public void setDeliveryManName(String deliveryManName) {
        this.deliveryManName = deliveryManName;
    }

    
    @Column(name="DELIVERY_MAN_PHONE", nullable=false)
    public long getDeliveryManPhone() {
        return this.deliveryManPhone;
    }
    
    public void setDeliveryManPhone(long deliveryManPhone) {
        this.deliveryManPhone = deliveryManPhone;
    }

    
    @Column(name="DELIVERY_MAN_LAT", nullable=false, precision=22, scale=0)
    public double getDeliveryManLat() {
        return this.deliveryManLat;
    }
    
    public void setDeliveryManLat(double deliveryManLat) {
        this.deliveryManLat = deliveryManLat;
    }

    
    @Column(name="DELIVERY_MAN_LONG", nullable=false, precision=22, scale=0)
    public double getDeliveryManLong() {
        return this.deliveryManLong;
    }
    
    public void setDeliveryManLong(double deliveryManLong) {
        this.deliveryManLong = deliveryManLong;
    }

    
    @Column(name="DELIVERY_MAN_NATIONAL_ID", nullable=false)
    public long getDeliveryManNationalId() {
        return this.deliveryManNationalId;
    }
    
    public void setDeliveryManNationalId(long deliveryManNationalId) {
        this.deliveryManNationalId = deliveryManNationalId;
    }

    
    @Column(name="DELIVERY_MAN_TOTAL_RATE", nullable=false, precision=12, scale=0)
    public float getDeliveryManTotalRate() {
        return this.deliveryManTotalRate;
    }
    
    public void setDeliveryManTotalRate(float deliveryManTotalRate) {
        this.deliveryManTotalRate = deliveryManTotalRate;
    }

    
    @Column(name="DELIVERY_MAN_RATE_COUNT", nullable=false)
    public int getDeliveryManRateCount() {
        return this.deliveryManRateCount;
    }
    
    public void setDeliveryManRateCount(int deliveryManRateCount) {
        this.deliveryManRateCount = deliveryManRateCount;
    }

    
    @Column(name="DELIVERY_MAN_ADDRESS_ID", nullable=false)
    public int getDeliveryManAddressId() {
        return this.deliveryManAddressId;
    }
    
    public void setDeliveryManAddressId(int deliveryManAddressId) {
        this.deliveryManAddressId = deliveryManAddressId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="deliveryMan")
@JsonManagedReference(value = "order-deliveryman")

    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


