package com.keroles.Pharmacy.Model.Entity;
// Generated Oct 22, 2021, 2:07:56 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Drugs generated by hbm2java
 */
@Entity
@Table(name="drugs"
    ,catalog="pharmacy"
)
public class Drugs  implements java.io.Serializable {


     private String drugsBarcode;
     private Company company;
     private String drugsName;
     private String type;
     private String dose;
     private double costPrice;
     private double sellingPrice;
     private Date productionDate;
     private Date expirationDate;
     private String place;
     private int quantity;
     private Set<OrderInfo> orderInfos = new HashSet(0);

    public Drugs() {
    }

	
    public Drugs(String drugsBarcode, Company company, String drugsName, String type, String dose, double costPrice, double sellingPrice, Date productionDate, Date expirationDate, String place, int quantity) {
        this.drugsBarcode = drugsBarcode;
        this.company = company;
        this.drugsName = drugsName;
        this.type = type;
        this.dose = dose;
        this.costPrice = costPrice;
        this.sellingPrice = sellingPrice;
        this.productionDate = productionDate;
        this.expirationDate = expirationDate;
        this.place = place;
        this.quantity = quantity;
    }
    public Drugs(String drugsBarcode, Company company, String drugsName, String type, String dose, double costPrice, double sellingPrice, Date productionDate, Date expirationDate, String place, int quantity, Set<OrderInfo> orderInfos) {
       this.drugsBarcode = drugsBarcode;
       this.company = company;
       this.drugsName = drugsName;
       this.type = type;
       this.dose = dose;
       this.costPrice = costPrice;
       this.sellingPrice = sellingPrice;
       this.productionDate = productionDate;
       this.expirationDate = expirationDate;
       this.place = place;
       this.quantity = quantity;
       this.orderInfos = orderInfos;
    }
   
     @Id 

    
    @Column(name="DRUGS_BARCODE", unique=true, nullable=false, length=100)
    public String getDrugsBarcode() {
        return this.drugsBarcode;
    }
    
    public void setDrugsBarcode(String drugsBarcode) {
        this.drugsBarcode = drugsBarcode;
    }

@ManyToOne(fetch=FetchType.LAZY)
@JsonBackReference(value = "drugs-company")
    @JoinColumn(name="COMPANY_ID", nullable=false)
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }

    
    @Column(name="DRUGS_NAME", nullable=false, length=50)
    public String getDrugsName() {
        return this.drugsName;
    }
    
    public void setDrugsName(String drugsName) {
        this.drugsName = drugsName;
    }

    
    @Column(name="TYPE", nullable=false, length=20)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="DOSE", nullable=false, length=10)
    public String getDose() {
        return this.dose;
    }
    
    public void setDose(String dose) {
        this.dose = dose;
    }

    
    @Column(name="COST_PRICE", nullable=false, precision=22, scale=0)
    public double getCostPrice() {
        return this.costPrice;
    }
    
    public void setCostPrice(double costPrice) {
        this.costPrice = costPrice;
    }

    
    @Column(name="SELLING_PRICE", nullable=false, precision=22, scale=0)
    public double getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(double sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PRODUCTION_DATE", nullable=false, length=10)
    public Date getProductionDate() {
        return this.productionDate;
    }
    
    public void setProductionDate(Date productionDate) {
        this.productionDate = productionDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRATION_DATE", nullable=false, length=10)
    public Date getExpirationDate() {
        return this.expirationDate;
    }
    
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    
    @Column(name="PLACE", nullable=false, length=20)
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }

    
    @Column(name="QUANTITY", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="drugs")
@JsonManagedReference(value = "drugs-orderinfo")

    public Set<OrderInfo> getOrderInfos() {
        return this.orderInfos;
    }
    
    public void setOrderInfos(Set<OrderInfo> orderInfos) {
        this.orderInfos = orderInfos;
    }


    public void Transfer(Drugs drugs){
        this.drugsBarcode=drugs.getDrugsBarcode()!=null?drugs.getDrugsBarcode():null;
        this.drugsName=drugs.getDrugsBarcode()!=null?drugs.getDrugsName():null;
        this.costPrice=drugs.getDrugsBarcode()!=null?drugs.getCostPrice():null;
        this.sellingPrice=drugs.getDrugsBarcode()!=null?drugs.getSellingPrice():null;
        this.dose=drugs.getDrugsBarcode()!=null?drugs.getDose():null;
        this.expirationDate=drugs.getDrugsBarcode()!=null?drugs.getExpirationDate():null;
        this.productionDate=drugs.getDrugsBarcode()!=null?drugs.getProductionDate():null;
        this.quantity=drugs.getDrugsBarcode()!=null?drugs.getQuantity():null;
        this.type=drugs.getDrugsBarcode()!=null?drugs.getType():null;
        this.place=drugs.getDrugsBarcode()!=null?drugs.getPlace():null;

    }


}


