package com.keroles.Pharmacy.Model.Entity;
// Generated Oct 22, 2021, 2:07:56 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderInfo generated by hbm2java
 */
@Entity
@Table(name="order_info"
    ,catalog="pharmacy"
)
public class OrderInfo  implements java.io.Serializable {


     private Integer orderInfoId;
     private Drugs drugs;
     private Order order;
     private String drugName;
     private float drugPrice;
     private int drugAmount;

    public OrderInfo() {
    }

    public OrderInfo(Drugs drugs, Order order, String drugName, float drugPrice, int drugAmount) {
       this.drugs = drugs;
       this.order = order;
       this.drugName = drugName;
       this.drugPrice = drugPrice;
       this.drugAmount = drugAmount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ORDER_INFO_ID", unique=true, nullable=false)
    public Integer getOrderInfoId() {
        return this.orderInfoId;
    }
    
    public void setOrderInfoId(Integer orderInfoId) {
        this.orderInfoId = orderInfoId;
    }

@ManyToOne(fetch=FetchType.LAZY)
@JsonBackReference(value = "drugs-orderinfo")

    @JoinColumn(name="DRUGS_BARCODE", nullable=false)
    public Drugs getDrugs() {
        return this.drugs;
    }
    
    public void setDrugs(Drugs drugs) {
        this.drugs = drugs;
    }

@ManyToOne(fetch=FetchType.LAZY)
@JsonBackReference(value = "order-orderinfo")
    @JoinColumn(name="ORDER_ID", nullable=false)
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }

    
    @Column(name="DRUG_NAME", nullable=false, length=100)
    public String getDrugName() {
        return this.drugName;
    }
    
    public void setDrugName(String drugName) {
        this.drugName = drugName;
    }

    
    @Column(name="DRUG_PRICE", nullable=false, precision=12, scale=0)
    public float getDrugPrice() {
        return this.drugPrice;
    }
    
    public void setDrugPrice(float drugPrice) {
        this.drugPrice = drugPrice;
    }

    
    @Column(name="DRUG_AMOUNT", nullable=false)
    public int getDrugAmount() {
        return this.drugAmount;
    }
    
    public void setDrugAmount(int drugAmount) {
        this.drugAmount = drugAmount;
    }




}


